CREATE TABLE products (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
description TEXT NOT NULL
);

CREATE TABLE packages (
id SERIAL PRIMARY KEY,
product_id INTEGER REFERENCES products(id),
name TEXT NOT NULL,
price INTEGER NOT NULL,
features TEXT NOT NULL
);

CREATE TABLE leads (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
email TEXT NOT NULL,
message TEXT NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);

